name: FlowSync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  http: ^1.6.0
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  open_filex: ^4.7.0

  intl: ^0.20.2
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^6.2.1
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - lib/assets/images/logo.png
     - lib/assets/images/logo1.png
     - lib/assets/images/splash_illustration.png
     - lib/assets/images/cammode.png
     - lib/assets/images/charts.png
     - lib/assets/images/pipes.png
     - lib/assets/images/storage.png
     - lib/assets/images/washbasin.png
     - lib/assets/images/paper_plane.png
     - lib/assets/images/homeimage.png
     - lib/assets/images/grass.png
     - lib/assets/images/gears.png
     - lib/assets/images/homeimage (2).png
     - lib/assets/images/grass-removebg-preview.png
     - lib/assets/images/gears-removebg-preview.png
     - lib/assets/images/warehouse.png
     - lib/assets/images/warehouse_rack.png 
     - lib/assets/images/warehouse_pipes.png        
     - lib/assets/images/crate.png    
     - lib/assets/images/inventory_rack.png   
     - lib/assets/images/inventory_header.png 
     - lib/assets/images/addproductheader.png  
     - lib/assets/images/purchase_screen_header.png
     - lib/assets/images/sales_screen_header.png
     - lib/assets/images/dashboard_screen_header.png

flutter_launcher_icons:
  image_path: "lib/assets/images/FlowSync_logo.png"
  android: true
  ios: true